{% set name = "sleapyfaces" %}
{% set version = "1.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sleapyfaces-{{ version }}.tar.gz
  sha256: 5615177d7808ed70c3964639b7bda9e69a237f5ec19f4a692dc612cdebdad48f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - click
    - pytest
    - pytest-cov
    - pandas
    - numpy
    - scipy
    - scikit-learn
    - pytables
    - ffmpeg-python
    - h5py
    - python-rapidjson
    - matplotlib-base
    - statsmodels
    - seaborn
    - geomstats
    - plotly
    - pathvalidate
    - more-itertools
    - python-configuration

test:
  imports:
    - sleapyfaces
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sleapyfaces/
  summary: A package for extracting facial expressions from SLEAP analyses
  dev_url: https://github.com/annie444/sleapyfaces
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - annie444
